src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('success/', TemplateView.as_view(template_name='success.html'), name='success'),

    path('account/', include('user_account.urls')),
    path('movies/', include('movie.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/movie/urls.py
from django.urls import path

from movie.views import MovieListView, MovieDetailsView

app_name = 'movie'

urlpatterns = [
    path('list/', MovieListView.as_view(), name='movie_list'),
    path('details/<int:pk>', MovieDetailsView.as_view(), name='movie_details'),
]

src/user_account/urls.py
from django.urls import path

from user_account.views import CreateUserAccountView, UserAccountLoginView, UserAccountLogoutView, \
    UserAccountUpdateView, user_account_update_profile

# app_name = 'user_account'

urlpatterns = [
    path('register/', CreateUserAccountView.as_view(), name='registration'),
    path('login/', UserAccountLoginView.as_view(), name='login'),
    path('logout/', UserAccountLogoutView.as_view(), name='logout'),
    # path('profile/', UserAccountUpdateView.as_view(), name='profile'),
    path('profile/', user_account_update_profile, name='profile'),
]

src/movie/models.py
from datetime import date

from django.db import models

# Create your models here.


class Movie(models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1024, null=True, blank=True)
    poster = models.ImageField(default='default_movie.jpg', upload_to='covers')
    genre = models.CharField(max_length=64, null=True, blank=True)
    producer = models.CharField(max_length=64, null=True, blank=True)
    release_date = models.DateField(default=date.today)
    budget = models.PositiveIntegerField(default=0, help_text="in dollars")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ('release_date',)

src/user_account/models.py
from django.db import models

# Create your models here.

from django.conf import settings
from django.contrib.auth.models import User


class UserAccountProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = models.ImageField(default='default.jpg', upload_to='pics')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} Profile'

src/user_account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from user_account.models import UserAccountProfile


class UserAccountRegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):  # <---- !!!!   .Meta
        # model = User
        fields = ("username", "first_name", "last_name", "email")

    """ unique email:"""
    def clean_email(self):

        email = self.cleaned_data['email']

        if User.objects.all().filter(email=email).exists():    # or  .count()>0
            raise ValidationError('Email already exists')

        return email

    def clean(self):

        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']

        if first_name == last_name:
            raise ValidationError('First and Last name must be different')

        return self.cleaned_data


class UserAccountProfileForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_email(self):

        email = self.cleaned_data['email']

        if User.objects.all().filter(email=email).exclude(id=self.instance.id).exists():
            raise ValidationError('Email already exists')

        return email


class UserProfileUpdateForm(ModelForm):
    class Meta:
        model = UserAccountProfile
        fields = ['image']

src/movie/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from movie.models import Movie


class MovieListView(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'movie_list.html'
    context_object_name = 'movie_list'
    login_url = reverse_lazy('login')
    paginate_by = 4

    def get_queryset(self):
        request = self.request
        qs = super().get_queryset()
        qs = qs.order_by('release_date')

        if request.GET.get('title'):
            qs = qs.filter(title=request.GET.get('title'))

        if request.GET.get('genre'):
            qs = qs.filter(genre=request.GET.get('genre'))

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Movie list'
        return context


class MovieDetailsView(LoginRequiredMixin, DetailView):
    model = Movie
    template_name = 'movie_details.html'
    context_object_name = 'movie'

src/user_account/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from user_account.forms import UserAccountRegistrationForm, UserAccountProfileForm, UserProfileUpdateForm


class CreateUserAccountView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = UserAccountRegistrationForm

    def get_success_url(self):
        return reverse('success')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Register new user'
        return context

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, "Great! New user has been successfully created!")
        return result


class UserAccountLoginView(LoginView):
    template_name = 'login.html'
    extra_context = {'title': 'Login as a user'}
    success_url = reverse_lazy('index')

    # def get_success_url(self):
    #     return reverse('profile')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, "Great! You've just successfully logged in!")
        return result


class UserAccountLogoutView(LogoutView):
    template_name = 'logout.html'
    extra_context = {'title': 'Logout from LMS'}


class UserAccountUpdateView(UpdateView):
    template_name = 'profile.html'
    extra_context = {'title': 'Edit current user profile'}
    form_class = UserAccountProfileForm
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return self.request.user

    # def get_success_url(self):
    #     return reverse('index')


@login_required
def user_account_update_profile(request):
    if request.method == 'POST':
        u_form = UserAccountProfileForm(request.POST, instance=request.user)
        p_form = UserProfileUpdateForm(request.POST,
                                       request.FILES,
                                       instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserAccountProfileForm(instance=request.user)
        p_form = UserProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'title': f'Edit {request.user.get_full_name()} user profile'
    }

    return render(
        request=request,
        template_name='profile.html',
        context=context
    )

src/movie/templates/includes/movie_table.html
{% if movie_list %}

    <table class="table table-hover" enctype="multipart/form-data">

        <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Poster</th>
              <th>Title</th>
              <th>Genre</th>
            </tr>
        </thead>

        {% for movie in movie_list %}
            <tr>
              <td> <a href="{% url 'movie:movie_details'  movie.id %}">DETAILS</a></td>
              <td>
                <div class="media">
                  <div class="img-circle.vert">
                    <img width="300" height="300"  src="{{ movie.poster.url }}">
                  </div>
                </div>
              </td>
              <td> {{ movie.title }}</td>
              <td> {{ movie.genre }}</td>
            </tr>
        {% endfor %}

    </table>

        <div class="p-1 m-1">
            {% include 'includes/pagination.html' %}
        </div>


{% else %}
    <p>Sorry, list is empty</p>

{% endif %}

src/movie/templates/movie_details.html
{% extends 'base.html' %}
<!--{% load crispy_forms_tags %}-->

{% block content %}

{% if movie %}

    <table class="table table-hover" enctype="multipart/form-data">

        <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Poster</th>
              <th>Title</th>
              <th>Genre</th>
            </tr>
        </thead>

            <tr>
              <td> {{ movie.id }}</td>
              <td>
                <div class="media">
                  <div class="img-circle.vert">
                    <img width="500" height="500"  src="{{ movie.poster.url }}">
                  </div>
                </div>
              </td>
              <td> {{ movie.title }}</td>
              <td> {{ movie.genre }}</td>
            </tr>

    </table>

    <p><b>DESCRIPTION </b>: {{ movie.description }}</p>
    <p><b>PRODUCER </b>: {{ movie.producer }}</p>
    <p><b>BUDGET </b>: {{ movie.budget }} <b>$</b></p>
    <p><b>RELEASE_DATE </b>: {{ movie.release_date }}</p>

{% else %}
    <p>Sorry, no details about the movie</p>

{% endif %}

{% endblock %}

src/movie/templates/movie_list.html
{% extends 'base.html' %}


{% block content %}

    <form>

     <div class="input-group mb-3">
         <div class="input-group-prepend">
             <span class="input-group-text" id="basic-addon1">Title</span>
         </div>
         <input name="title" type="text" class="form-control" placeholder="Title" aria-label="title" aria-describedby="basic-addon1">

         <div class="input-group-prepend">
             <span class="input-group-text" id="basic-addon1">Genre</span>
         </div>
         <input name="genre" type="text" class="form-control" placeholder="Genre" aria-label="genre" aria-describedby="basic-addon1">

         <button type="submit" class="btn btn-success">Search</button>
     </div>

    </form>


    {% include 'includes/movie_table.html' %}


{% endblock %}

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user_account/css/base.css' %}">

</head>


<body>


<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">


        <a class="navbar-brand" href="{% url 'index' %}">MOVIE</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'movie:movie_list' %}">Movie-List <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" >News</a>
                </li>

<!--                      <li class="nav-item dropdown">-->
<!--                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                          Dropdown-->
<!--                        </a>-->
<!--                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--                          <a class="dropdown-item" href="#">Action</a>-->
<!--                          <a class="dropdown-item" href="#">Another action</a>-->
<!--                          <div class="dropdown-divider"></div>-->
<!--                          <a class="dropdown-item" href="#">Something else here</a>-->
<!--                        </div>-->
<!--                      </li>-->
<!--                      <li class="nav-item">-->
<!--                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--                      </li>-->
            </ul>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <img alt="Profile pic" width="40" height="40" class="rounded-circle" src="{{ user.profile.image.url }}">
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'profile' %}">Profile ({{ user.username}})</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'registration' %}">Register </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>

<!--            <form class="form-inline my-2 my-lg-0">-->
<!--                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--            </form>-->
        </div>
    </nav>
</div>


<div class="container">

        <div class="p-1 m-1">
            {% include 'includes/messages.html' %}
        </div>

<!--    <h2 class="p-4 mx-auto">{{ title }}</h2>-->
<!--    <p></p>-->
        <div class="border rounded text-center p-3 m-3 bg-light text-dark" >
            <h1>{% block title %}{{ title }}{% endblock %}</h1>
        </div>


    {% block  content %}

    {% endblock %}



</div>

</body>

</html>

src/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

src/templates/includes/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">

        {% if page_obj.has_previous %}
<!--            <li class="page-item"><a class="page-link" href="?page=1&{{ query_params }}">First</a></li>-->
            <li class="page-item"><a class="page-link" href="?page=1&{{ request.query_params }}">First</a></li>
{#            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ query_params }}" tabindex="-1"> << </a>#}
        {% endif %}

<!--        {% with offset=3 %}-->

            {% for number_page in page_obj.paginator.page_range %}

                {% if number_page == page_obj.number %}
                    <li class="page-item active">
<!--                        <a class="page-link" href="#"&{{ query_params }}>{{ page_obj.number }} <span class="sr-only">(current)</span></a>-->
                        <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                    </li>
{#                {% elif number_page > page_obj.number|add:-offset and number_page < page_obj.number|add:offset  %}#}
                {% elif number_page > page_obj.number|add:-3 and number_page < page_obj.number|add:3  %}
                    <li class="page-item">
<!--                      <a class="page-link" href="?page={{ number_page }}&{{ query_params }}">{{ number_page }} </a>-->
                      <a class="page-link" href="?page={{ number_page }}&{{ request.query_params }}">{{ number_page }} </a>
                    </li>
                {% endif %}

            {% endfor %}


<!--        {% endwith %}-->

        {% if page_obj.has_next %}
{#            <li class="page-item">#}
{#                <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ query_params }}"> >> </a>#}
{#            </li>#}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ query_params }}">Last</a></li>
        {% endif %}


    </ul>
</nav>

src/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Welcome to the MOVIE</h1>

{% endblock %}

src/templates/success.html
{% extends 'base.html' %}

{% block content %}

    <h1>User successfully registered </h1>

    <a href="{% url 'index' %}" class="btn btn-light">Start page</a>

{% endblock %}

src/user_account/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

        <button type="submit" class="btn btn-success">Login</button>
        <a href="{% url 'index' %}" class="btn btn-danger">Cancel</a>
    </form>

{% endblock %}

src/user_account/templates/logout.html
{% extends 'base.html' %}

{% block content %}

    <h3>User has been logged out</h3>
    <a href="{% url 'login' %}" class="btn btn-success">Login</a>

{% endblock %}

src/user_account/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="media">
        <div class="img-circle.vert">
            <img class="rounded-circle p-1 m-1" width="300" height="300"  src="{{ user.profile.image.url }}">
        </div>
{#        <img class="rounded-circle p-1 m-1" width="300" height="{{ user.profile.image.height }}"  src="{{ user.profile.image.url }}">#}
{#        <img class="img-circle p-1 m-1"  src="{{ user.profile.image.url }}">#}
        <div class="media-body  p-3 m-3">
            <h2 class="account-heading">{{ user.username }}</h2>
            <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>

    <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
<!--            {{ form|crispy }}-->
            {{ u_form|crispy }}
            {{ p_form|crispy }}

        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'index' %}" class="btn btn-light">Cancel</a>
    </form>

{% endblock %}

src/user_account/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Register</button>
        <a href="{% url 'index' %}" class="btn btn-light">Cancel</a>
    </form>

{% endblock %}